[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/auth/*"
  to = "/api/auth/:splat"
  status = 200